spring:
  datasource:
    username: sandeep
    url: jdbc:postgresql://localhost:5432/demo
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'